index-page
SvetikBaglay/coursera pull request #1
Opened 2019-10-30 18:24 UTC by SvetikBaglay

2019-10-30 18:59 UTC, klamath commented on stylesheet.html
> +    <link rel="stylesheet" href="/home/cvetok/www/coursera/coursera.css" type="text/css">
`/home/cvetok/www/coursera/coursera.css` => `./coursera.css`

2019-10-30 19:00 UTC, klamath commented on stylesheet.html
> +          <div class="box-inform">
Кажеться, что `block-inform` и `box-inform` можно во что-то одно объединить.

2019-10-30 19:01 UTC, klamath commented on stylesheet.html
> +            </div>
Отступы заболели

2019-10-30 19:02 UTC, klamath commented on stylesheet.html
> +                    </span>
Странно, что `</span>` на новой строке. Хотя во всех остальных местах в конце строки.

2019-10-30 19:04 UTC, klamath commented on stylesheet.html
> +            <div class="business__button"><a href="#">Подробнее...</a>
Здесь надо либо ссылку на новую строку перенести. Либо `</div>` в конец строки.

2019-10-30 19:05 UTC, klamath commented on stylesheet.html
> +            <p class="footer__list-text">Сообщество</p>
Кажеться, что это заголовок должен быть?
`<p class="footer__list-text"` => `<h6 class="footer__list-text"`

2019-10-30 19:06 UTC, klamath commented on stylesheet.html
> +      <div class="footer">
`<footer>` и `<div class="footer">` можно объединить.

2019-10-30 19:07 UTC, klamath commented on stylesheet.html
> +                <a href="#" alt="">Get job-ready for an in-demand career</a></h2>
Вроде у ссылки нет аттрибута `alt`

2019-10-30 19:08 UTC, klamath commented on stylesheet.html
> +              <a href="#"><img src="/home/cvetok/www/coursera/picture/partners/Illinois.jpg" alt=""</a>
Тег `img` не закрыт

2019-10-30 19:08 UTC, klamath commented on stylesheet.html
> +          <a  href="#" class="logo__authorization-info">Для организаций</a>
Одного пробела достаточно

2019-10-30 19:10 UTC, klamath commented on stylesheet.html
> +            <a href="#"><img src="/home/cvetok/www/coursera/picture/logo.jpg"></a>
Относительные путь

2019-10-30 19:11 UTC, klamath commented on stylesheet.html
> +              Company Logos
Здесь какжеться самих логотипов не хватает.

2019-10-30 19:11 UTC, klamath commented on stylesheet.html
> +            </div>
А здесь текста?

2019-10-31 17:10 UTC, klamath commented on stylesheet.html
> +    <link rel="stylesheet" href="/home/cvetok/www/coursera/coursera.css" type="text/css">
Все еще надо зделать путь относительным.

2019-10-31 17:43 UTC, klamath requested changes
Внимательнее следи на классами.

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +          <div class="inform-box">
`inform` элемент внутри блока должен быть `inform__box`

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +            <div class="box-partners">
Здесь тоже самое `block-partners` и `box-partners` никак не связаны

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +            </div>
Отступы все еще болеют.

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +            <div class="box-promotion">
`block-promotion` и `box-promotion` никак не связяны.

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +              <h2 class="box-promotion__text">
У `<h2>` нет закрывающего тега

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +            <div class="more-promotion">
`skills-promotion` и `more-promotion` не имеют никакого отношения к `box-promotion`

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +            <div class="all-partners">
`all-partners` никак не связан с `box-partners`

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +  </header>
Отступы у `</header>` не правильные.

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +      <div class="logo">
Почему здесь `logo`? У тебя весь хеадер логотип? 
`<div class="logo">` надо выпилить совсем. Оставить только `<header class="header">` и все дочерние элементы переделать.

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +                    <span class="work__list__num">1</span>
`work__list__num` что здесь элемент, а что блок? 
Правильно так: `work__lisk-num`, `work` -- блок, а `list_num` его элемент.

2019-10-31 17:43 UTC, klamath commented on stylesheet.html
> +    <div class="footer">
Почему победил `<div class="footer">`, а не `<footer class="footer">`?

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  position: absolute;
Теперь все кнопки, где бы мы их не поставили, будут с `position: absolute;`. Не надо так.

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +}
У всех кнопок в `:before` будет такая иконка.

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +button:before {
Разделяй блоки пустой строкой.

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  color: #fff;
Кажеться, что `color: #fff;` здесь не нужно писать.

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  font-size: 14px;
Кажеться, что `font-size: 14px;` можно использовать, как дефолтный размер и перенести его в `body {}`

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  font-size: 14px;
А отсюда и из всех остальных мест -- выпилить.

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +}
Теперь у всех ссылок не будет подчеркивания.

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  width: 1310px;
Здесь точно надо `1310px`? Может можно что-то вроде `100%` задать?

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  margin-right: auto;
margin: 0 auto;

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  margin-right: auto;
margin: 0 auto;

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +}
Не надо так. Теперь все списки будут с такими свойствами. 
`.work__list ol {`

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  background-position: top-right;
`background-position: top-right;` => `background-position: top right;`

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  color: #0000FF;
`#00f`

2019-10-31 17:43 UTC, klamath commented on coursera.css
> +  width: 151.333px;
Или 151 или 152.

2019-11-01 11:56 UTC, SvetikBaglay commented on stylesheet.html
> +          <div class="inform-box">
+

2019-11-01 11:56 UTC, SvetikBaglay commented on stylesheet.html
> +            <div class="box-partners">
+

2019-11-01 12:50 UTC, SvetikBaglay commented on stylesheet.html
> +              <h2 class="box-promotion__text">
<h2 ><a></a></h2>

2019-11-05 17:15 UTC, merged